import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from threading import Event
from typing import Callable, Iterable

VIDEO_EXTENSIONS = {".strm", ".mp4", ".mkv", ".avi", ".mov", ".wmv"}


@dataclass
class TaskResult:
    success_count: int
    failed_count: int
    skipped_count: int
    total_files: int


class ThumbnailScraper:
    def __init__(self, config: dict):
        self.config = config

    def _iter_video_files(self, root: Path) -> Iterable[Path]:
        if not root.exists():
            return []
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in VIDEO_EXTENSIONS:
                yield path

    def _probe_duration(self, file_path: Path) -> float | None:
        command = [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(file_path),
        ]
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=False,
                timeout=30,
            )
            if result.returncode != 0:
                return None
            return float(result.stdout.strip())
        except Exception:
            return None

    def _write_nfo(self, video_path: Path) -> None:
        nfo_path = video_path.with_suffix(".nfo")
        if nfo_path.exists() and not self.config.get("overwrite", False):
            return
        nfo_path.write_text(
            "<movie>\n  <title>{}</title>\n  <plot>Generated by StrmThumbnail</plot>\n</movie>\n".format(video_path.stem),
            encoding="utf-8",
        )

    def _capture_frame(self, video_path: Path, output_path: Path, second: float) -> bool:
        if output_path.exists() and not self.config.get("overwrite", False):
            return True
        command = [
            "ffmpeg",
            "-y" if self.config.get("overwrite", False) else "-n",
            "-ss",
            f"{max(second, 1):.2f}",
            "-i",
            str(video_path),
            "-frames:v",
            "1",
            str(output_path),
        ]
        result = subprocess.run(command, capture_output=True, text=True, check=False)
        return result.returncode == 0

    def run(
        self,
        mode: str,
        stop_event: Event,
        log_callback: Callable[[str], None],
        progress_callback: Callable[[int, int, str], None],
    ) -> TaskResult:
        media_root = Path(self.config.get("media_path", "/media"))
        files = list(self._iter_video_files(media_root))

        total = len(files)
        success = 0
        failed = 0
        skipped = 0

        log_callback(f"扫描目录: {media_root}")
        log_callback(f"匹配视频文件数: {total}")

        for index, file_path in enumerate(files, start=1):
            if stop_event.is_set():
                log_callback("收到停止信号，任务即将退出。")
                progress_callback(index - 1, total, "stopped")
                break

            progress_callback(index, total, "running")
            log_callback(f"[{index}/{total}] 处理: {file_path}")

            poster_enabled = bool(self.config.get("generate_poster", True))
            fanart_enabled = bool(self.config.get("generate_fanart", True))
            nfo_enabled = bool(self.config.get("generate_nfo", False))

            poster_path = file_path.with_name(f"{file_path.stem}-poster.jpg")
            fanart_path = file_path.with_name(f"{file_path.stem}-fanart.jpg")

            if mode == "incremental":
                poster_exists_or_disabled = (not poster_enabled) or poster_path.exists()
                fanart_exists_or_disabled = (not fanart_enabled) or fanart_path.exists()
                nfo_exists_or_disabled = (not nfo_enabled) or file_path.with_suffix(".nfo").exists()
                if poster_exists_or_disabled and fanart_exists_or_disabled and nfo_exists_or_disabled:
                    skipped += 1
                    log_callback("增量模式：目标文件已存在，跳过。")
                    continue

            duration = self._probe_duration(file_path)
            if (poster_enabled or fanart_enabled) and duration is None:
                failed += 1
                log_callback("无法获取时长，跳过抽帧（ffprobe 失败）。")
                continue

            ok = True
            if poster_enabled and duration is not None:
                poster_second = duration * float(self.config.get("poster_percent", 10)) / 100
                ok = ok and self._capture_frame(file_path, poster_path, poster_second)

            if fanart_enabled and duration is not None:
                fanart_second = duration * float(self.config.get("fanart_percent", 50)) / 100
                ok = ok and self._capture_frame(file_path, fanart_path, fanart_second)

            if nfo_enabled:
                self._write_nfo(file_path)

            if ok:
                success += 1
            else:
                failed += 1

            time.sleep(0.01)

        processed = success + failed + skipped
        if processed < total and stop_event.is_set():
            skipped += total - processed

        return TaskResult(
            success_count=success,
            failed_count=failed,
            skipped_count=skipped,
            total_files=total,
        )
