from __future__ import annotations

import threading
from dataclasses import dataclass
from pathlib import Path

try:
    import psutil
except ImportError:
    psutil = None

from .network_guard import run_with_retry


class QPSLimiter:
    def __init__(self, qps: float = 2.0):
        self.interval = 1.0 / max(0.1, qps)
        self.last_shot = 0.0
        self._lock = threading.Lock()

    def wait(self) -> None:
        import time

        with self._lock:
            now = time.time()
            wait_time = self.interval - (now - self.last_shot)
            if wait_time > 0:
                time.sleep(wait_time)
            self.last_shot = time.time()


@dataclass(slots=True)
class ScrapeOptions:
    full: bool
    generate_poster: bool
    generate_fanart: bool
    generate_nfo: bool
    overwrite: bool
    poster_pct: float
    fanart_pct: float


@dataclass(slots=True)
class ProcessResult:
    status: str
    path: Path
    message: str = ""
    output_size: int = 0
    downloaded_bytes: int = 0


def _read_url(strm_path: Path) -> str:
    try:
        with strm_path.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if line and not line.startswith("#"):
                    return line
    except OSError:
        return ""
    return ""


def _net_recv_bytes() -> int:
    if psutil is None:
        return 0
    return int(psutil.net_io_counters().bytes_recv)


def get_video_duration(url: str) -> float | None:
    cmd = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "default=noprint_wrappers=1:nokey=1",
        url,
    ]
    result = run_with_retry(cmd, timeout=20, retries=1)
    if not result.ok:
        return None
    try:
        return float(result.stdout.strip())
    except (TypeError, ValueError):
        return None


def extract_frame(url: str, output_path: Path, timestamp: float) -> tuple[bool, int]:
    cmd = [
        "ffmpeg",
        "-y",
        "-ss",
        f"{round(timestamp, 2)}",
        "-i",
        url,
        "-map",
        "0:v:0",
        "-frames:v",
        "1",
        "-q:v",
        "3",
        "-f",
        "image2",
        str(output_path),
    ]
    result = run_with_retry(cmd, timeout=60, retries=1)
    if result.ok and output_path.exists():
        return True, int(output_path.stat().st_size)
    return False, 0


def generate_nfo(strm_path: Path, duration: float | None) -> bool:
    nfo_path = strm_path.with_suffix(".nfo")
    title = strm_path.stem
    runtime = int((duration or 0) / 60)

    content = f"""<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?>
<movie>
  <title>{title}</title>
  <originaltitle>{title}</originaltitle>
  <runtime>{runtime}</runtime>
  <plot>Auto generated by STRM Thumbnail</plot>
</movie>"""

    try:
        nfo_path.write_text(content, encoding="utf-8")
        return True
    except OSError:
        return False


def process_single_strm(
    strm_path: Path,
    options: ScrapeOptions,
    limiter: QPSLimiter,
) -> ProcessResult:
    poster_path = strm_path.with_suffix(".jpg")
    fanart_path = Path(str(strm_path).replace(".strm", "-fanart.jpg"))
    nfo_path = strm_path.with_suffix(".nfo")

    mode_full = options.full or options.overwrite

    if not mode_full:
        need_poster = options.generate_poster and not poster_path.exists()
        need_fanart = options.generate_fanart and not fanart_path.exists()
        need_nfo = options.generate_nfo and not nfo_path.exists()
        if not (need_poster or need_fanart or need_nfo):
            return ProcessResult(status="skipped", path=strm_path, message="already exists")
    else:
        for p in [poster_path, fanart_path, nfo_path]:
            if p.exists():
                p.unlink(missing_ok=True)

    url = _read_url(strm_path)
    if not url:
        return ProcessResult(status="failed", path=strm_path, message="empty strm")

    limiter.wait()

    before = _net_recv_bytes()
    duration = get_video_duration(url)
    after = _net_recv_bytes()
    downloaded = max(0, after - before)

    if not duration:
        return ProcessResult(status="failed", path=strm_path, message="ffprobe failed", downloaded_bytes=downloaded)

    success = True
    output_size = 0
    if options.generate_poster:
        ok, size = extract_frame(url, poster_path, duration * options.poster_pct)
        success = success and ok
        output_size += size
    if options.generate_fanart:
        ok, size = extract_frame(url, fanart_path, duration * options.fanart_pct)
        success = success and ok
        output_size += size
    if options.generate_nfo:
        success = success and generate_nfo(strm_path, duration)

    if success:
        return ProcessResult(status="success", path=strm_path, output_size=output_size, downloaded_bytes=downloaded)
    return ProcessResult(status="failed", path=strm_path, message="task failed", output_size=output_size, downloaded_bytes=downloaded)
